config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'home#index'
  get 'home/about'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container">
   
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <a class="navbar-brand" href="#">Awakening</a>
        </div>
    
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Home', root_path, class:"btn btn-primary" %></li>
                <li><%= link_to 'About', home_about_path, class:"btn btn-primary" %></li>
                <li><%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-primary" %></li>
                <li><%= link_to 'Login', new_user_session_path, class:"btn btn-primary" %></li>
                <li><%= link_to 'Edit Profile', edit_user_registration_path, class:"btn btn-primary" %></li>
                <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete, class:"btn btn-primary" %></li>
            </ul>
        </div>
        
    </div>
</nav>

app/views/home/about.html.erb
<h1>About Me</h1>

<p>
To start, my name is Subaki. Just kidding. I wish though I do know a lot of origami and one of my favorite classes is the flier.
My real name is Jesus Mendoza and like I mentioned before I'm just joining the FE fandom. Because of the time and effort that
I am putting on this website and my education I'm still unsure about when or where to start delving into the roots of this
amazing franchise. I will be doing my best to make this a user friendly and functional environment for all of those who's
"sword hands are twitching" and "blood is aching" for a site like this. I will also be inviting feedback to make this site great.
</p>

app/views/home/index.html.erb
<div class='jumbotron center'>
    
    <h1>Fanpage Awakening</h1>
    
    <p>Hello! This is a fanpage for everything related to Fire Emblem. Sorry hardcore fans I have no knowledge of the games prior to Awakening.
    I know, you want to release your wrath upon me but let's all get along. This page (as well as my mind) is in development so stay tuned for new
    things to come.<br>Thanks for your support and cooperation.</p>
    
    <%= link_to 'Login', new_user_session_path, class:"btn btn-primary" %>
    <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-primary" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awakening</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'home/header' %>

<div class='container'>
  
<% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class:"alert alert-info") %>
<% end %>
 
<%= yield %>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading"><h1>Editing Post</h1></div>
    
    <div class="panel-body">
        <%= render 'form' %>
    </div>
    
    <div class="panel-footer">    
        <%= link_to 'Show', @post, class:"btn btn-primary" %> |
        <%= link_to 'Back', posts_path, class:"btn btn-primary" %>
    </div>
    
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-heading">
  <div class="panel-heading"><h1>Listing Posts</h1></div>
  
  <div class="panel-body">
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.description %></td>
            <td><%= link_to 'Show', post, class:"btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_post_path(post), class:"btn btn-primary" %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
    
  <div class="panel-footer">
    <%= link_to 'New Post', new_post_path, class:"btn btn-primary" %>
  </div>
  
</div>

app/views/posts/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading"><h1>New Post</h1></div>
    
    <div class="panel-body">
        <%= render 'form' %>
    </div>
    
    <div class="panel-footer">    
        <%= link_to 'Back', posts_path, class:"btn btn-primary" %>
    </div>
    
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading"><strong>Description:</strong></div>
  
  <div class="panel-body">
    <p>
      <%= @post.description %>
    </p>
  </div>
  
  <div class="panel-footer">
    <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-primary" %> |
    <%= link_to 'Back', posts_path, class:"btn btn-primary" %>
  </div>

</div>